# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodExpert' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for FoodExpert
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'FirebaseCore'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SDWebImage'
end
